"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "src/main/resources/assets/pipeorgans/lang/en_us.json",
    "translation": "src/main/resources/assets/pipeorgans/lang/%two_letters_code%.json",
    "languages_mapping": {
      "two_letters_code": {
        "cs": "cs_cz",
        "nl": "nl_nl",
        "fr": "fr_fr",
        "de": "de_de",
        "pl": "pl_pl",
        "ru": "ru_ru",
        "es": "es_es"
      }
    }
  }
]