package com.finchy.pipeorgans.data.advancement;

import com.finchy.pipeorgans.PipeOrgans;
import com.tterrag.registrate.util.entry.BlockEntry;
import com.tterrag.registrate.util.entry.ItemProviderEntry;
import net.minecraft.advancements.Advancement;
import net.minecraft.advancements.CriterionTriggerInstance;
import net.minecraft.advancements.critereon.*;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;

import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.UnaryOperator;

public class PipeOrgansAdvancement {

    static final ResourceLocation BACKGROUND = ResourceLocation.fromNamespaceAndPath("minecraft","block/cut_copper.png");
    // title lang entries are advancement.pipeorgans.[id]
    // description lang entries are advancement.pipeorgans.[id].desc
    static final String LANG_PREFIX = "advancement." + PipeOrgans.MOD_ID + ".";
    static final String SECRET_SUFFIX = "\n§7(Hidden Advancement)";

    private final Advancement.Builder builder = Advancement.Builder.advancement(); // minecraft's advancement builder (not to be confused with the Builder b);
    private PipeOrgansAdvancement parent;
    private final Builder pipeOrgansBuilder = new Builder();

    Advancement datagenResult; // the advancement that's ultimately generated by datagen

    private String id;
    private String title;
    private String description;

    public PipeOrgansAdvancement(String id, UnaryOperator<Builder> b) {
        this.id = id;
        b.apply(pipeOrgansBuilder); // apply the specified modifications to a new builder
        // this lets you just type "b -> b.icon()" (e.g.) instead of "new PipeOrgansAdvancement.Builder().icon()"
        
        if (!pipeOrgansBuilder)

        builder.display(pipeOrgansBuilder.icon, Component.translatable(titleKey()),
                Component.translatable(descriptionKey()).withStyle(s -> s.withColor(0xDBA213)),
                id.equals("root") ? BACKGROUND : null, pipeOrgansBuilder.frameType, pipeOrgansBuilder.showToast, pipeOrgansBuilder.announceToChat, pipeOrgansBuilder.hidden);

        if (t.hidden)
            description += SECRET_SUFFIX;

        AllAdvancements.ENTRIES.add(this);
    }

    private String titleKey() {
        return LANG_PREFIX + id;
    }

    private String descriptionKey() {
        return titleKey() + ".desc";
    }

    public boolean isAlreadyAwardedTo(Player player) {
        if (!(player instanceof ServerPlayer sp))
            return true;
        Advancement advancement = sp.getServer()
                .getAdvancements()
                .getAdvancement(PipeOrgans.asResource(id));
        if (advancement == null)
            return true;
        return sp.getAdvancements()
                .getOrStartProgress(advancement)
                .isDone();
    }

    /*public void awardTo(Player player) {
        if (!(player instanceof ServerPlayer sp))
            return;
        if (builtinTrigger == null)
            throw new UnsupportedOperationException(
                    "Advancement " + id + " uses external Triggers, it cannot be awarded directly");
        builtinTrigger.trigger(sp);
    }
    */

    void save(Consumer<Advancement> t) {
        if (parent != null)
            builder.parent(parent.datagenResult);
        datagenResult = builder.save(t, PipeOrgans.asResource(id)
                .toString());
    }

    void provideLang(BiConsumer<String, String> consumer) {
        consumer.accept(titleKey(), title);
        consumer.accept(descriptionKey(), description);
    }

    class Builder {

        private FrameType frameType = FrameType.TASK;
        private boolean showToast = true;
        private boolean announceToChat = false;
        private boolean hidden = false;

        private int keyIndex = 0;
        private ItemStack icon;

        Builder after(PipeOrgansAdvancement other) { // sets this advancement's parent advancement
            PipeOrgansAdvancement.this.parent = other;
            return this;
        }

        Builder icon(ItemProviderEntry<?> item) { // sets icon from an ItemProviderEntry
            return icon(item.asStack());
        }

        Builder icon(ItemLike item) { // sets icon from an ItemLike
            return icon(new ItemStack(item));
        }

        Builder icon(ItemStack stack) { // sets icon from an ItemStack
            icon = stack;
            return this;
        }

        Builder title(String title) { // sets the title
            PipeOrgansAdvancement.this.title = title;
            return this;
        }

        Builder description(String description) { // sets the description
            PipeOrgansAdvancement.this.description = description;
            return this;
        }

        Builder frame(FrameType frameType) { // sets the frameType
            this.frameType = frameType;
            return this;
        }

        // because create made their TaskType enum PRIVATE. BOOOOO

        Builder silentTask() {
            showToast = false;
            return this;
        }

        // the NORMAL TaskType is just default settings, so there's no method for it

        Builder noisyTask() {
            announceToChat = true;
            return this;
        }

        Builder expertTask() {
            frameType = FrameType.GOAL;
            announceToChat = true;
            return this;
        }

        Builder secretTask() {
            frameType = FrameType.GOAL;
            announceToChat = true;
            hidden = true;
            return this;
        }

        Builder whenBlockPlaced(BlockEntry<?> blockEntry) { // grant advancement when the specified BlockEntry is placed
            return trigger(ItemUsedOnLocationTrigger.TriggerInstance.placedBlock(blockEntry.get()));
        }

        Builder whenBlockPlaced(Block block) { // grant advancement when the specified block is placed
            return trigger(ItemUsedOnLocationTrigger.TriggerInstance.placedBlock(block));
        }

        Builder whenIconCollected() { // grant advancement when the icon item is collected
            return trigger(InventoryChangeTrigger.TriggerInstance.hasItems(icon.getItem()));
        }

        Builder whenItemCollected(ItemProviderEntry<?> item) { // grant advancement when the specified ItemProviderEntry is collected
            return whenItemCollected(item.asStack()
                    .getItem());
        }

        Builder whenItemCollected(ItemLike itemProvider) { // grant advancement when the specified ItemLike is collected
            return trigger(InventoryChangeTrigger.TriggerInstance.hasItems(itemProvider));
        }

        Builder whenItemCollected(TagKey<Item> tag) { // grant advancement when any item with the specified tag is collected
            return trigger(InventoryChangeTrigger.TriggerInstance
                    .hasItems(new ItemPredicate(tag, null, MinMaxBounds.Ints.ANY, MinMaxBounds.Ints.ANY,
                            EnchantmentPredicate.NONE, EnchantmentPredicate.NONE, null, NbtPredicate.ANY)));
        }

        Builder awardedForFree() { // grant automatically (used for root advancement)
            return trigger(InventoryChangeTrigger.TriggerInstance.hasItems(new ItemLike[]{}));
        }

        Builder trigger(CriterionTriggerInstance trigger) { // set a CriterionTriggerInstance for the advancement
            builder.addCriterion(String.valueOf(keyIndex), trigger);
            keyIndex++;
            return this;
        }
    }
}
