package com.finchy.pipeorgans.data.advancement;

import com.finchy.pipeorgans.PipeOrgans;
import com.tterrag.registrate.util.entry.BlockEntry;
import com.tterrag.registrate.util.entry.ItemProviderEntry;
import net.minecraft.advancements.*;
import net.minecraft.advancements.critereon.*;
import net.minecraft.core.HolderLookup;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;

import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.UnaryOperator;

public class PipeOrgansAdvancement {

    static final ResourceLocation BACKGROUND = ResourceLocation.withDefaultNamespace("textures/block/cut_copper.png");
    // title lang entries are advancement.pipeorgans.[id]
    // description lang entries are advancement.pipeorgans.[id].desc
    static final String LANG_PREFIX = "advancement." + PipeOrgans.MOD_ID + ".";
    static final String SECRET_SUFFIX = "\n§7(Hidden Advancement)";

    private final Advancement.Builder mcBuilder = Advancement.Builder.advancement(); // minecraft's advancement builder (not to be confused with the Builder b);
    private PipeOrgansAdvancement parent;
    private final Builder pipeOrgansBuilder = new Builder();

    AdvancementHolder datagenResult; // the advancement that's ultimately generated by datagen

    private String id;
    private String title;
    private String description;

    public PipeOrgansAdvancement(String id, UnaryOperator<Builder> b) {
        this.id = id;
        b.apply(pipeOrgansBuilder); // apply the specified modifications to a new builder
        // this lets you just type "b -> b.icon()" (e.g.) instead of "new PipeOrgansAdvancement.Builder().icon()"

        if (pipeOrgansBuilder.hidden)
            description += SECRET_SUFFIX;

        AllAdvancements.ENTRIES.add(this);
    }

    private String titleKey() {
        return LANG_PREFIX + id;
    }

    private String descriptionKey() {
        return titleKey() + ".desc";
    }

    public boolean isAlreadyAwardedTo(Player player) {
        if (!(player instanceof ServerPlayer sp))
            return true;
        AdvancementHolder advancement = sp.getServer()
                .getAdvancements()
                .get(PipeOrgans.asResource(id));
        if (advancement == null)
            return true;
        return sp.getAdvancements()
                .getOrStartProgress(advancement)
                .isDone();
    }

    void save(Consumer<AdvancementHolder> t, HolderLookup.Provider registries) {
        if (parent != null)
            mcBuilder.parent(parent.datagenResult);
        
        if (pipeOrgansBuilder.func != null)
            pipeOrgansBuilder.icon(pipeOrgansBuilder.func.apply(registries));

        mcBuilder.display(pipeOrgansBuilder.icon, Component.translatable(titleKey()),
                Component.translatable(descriptionKey()).withStyle(s -> s.withColor(0xDBA213)),
                id.equals("root") ? BACKGROUND : null, pipeOrgansBuilder.advancementType, pipeOrgansBuilder.showToast,
                pipeOrgansBuilder.announceToChat, pipeOrgansBuilder.hidden);
        
        datagenResult = mcBuilder.save(t, PipeOrgans.asResource(id)
                .toString());
    }

    void provideLang(BiConsumer<String, String> consumer) {
        consumer.accept(titleKey(), title);
        consumer.accept(descriptionKey(), description);
    }

    class Builder {

        private AdvancementType advancementType = AdvancementType.TASK;
        private boolean showToast = true;
        private boolean announceToChat = false;
        private boolean hidden = false;

        private int keyIndex = 0;
        private ItemStack icon;
        private Function<HolderLookup.Provider, ItemStack> func;

        Builder after(PipeOrgansAdvancement other) { // sets this advancement's parent advancement
            PipeOrgansAdvancement.this.parent = other;
            return this;
        }

        Builder icon(ItemProviderEntry<?, ?> item) { // sets icon from an ItemProviderEntry
            return icon(item.asStack());
        }

        Builder icon(ItemLike item) { // sets icon from an ItemLike
            return icon(new ItemStack(item));
        }

        Builder icon(ItemStack stack) { // sets icon from an ItemStack
            icon = stack;
            return this;
        }

        Builder title(String title) { // sets the title
            PipeOrgansAdvancement.this.title = title;
            return this;
        }

        Builder description(String description) { // sets the description
            PipeOrgansAdvancement.this.description = description;
            return this;
        }

        // because create didn't make their TaskType enum public. BOOOOO

        Builder advancementType(AdvancementType type) { // sets the frameType
            this.advancementType = type;
            return this;
        }

        Builder silent() {
            showToast = false;
            return this;
        }

        // the NORMAL TaskType is just default settings, so there's no method for it

        Builder noisy() {
            announceToChat = true;
            return this;
        }

        Builder expert() {
            advancementType = AdvancementType.GOAL;
            announceToChat = true;
            return this;
        }

        Builder secret() {
            advancementType = AdvancementType.GOAL;
            announceToChat = true;
            hidden = true;
            return this;
        }

        Builder whenBlockPlaced(BlockEntry<?> blockEntry) { // grant advancement when the specified BlockEntry is placed
            return trigger(ItemUsedOnLocationTrigger.TriggerInstance.placedBlock(blockEntry.get()));
        }

        Builder whenBlockPlaced(Block block) { // grant advancement when the specified block is placed
            return trigger(ItemUsedOnLocationTrigger.TriggerInstance.placedBlock(block));
        }

        Builder whenIconCollected() { // grant advancement when the icon item is collected
            return trigger(InventoryChangeTrigger.TriggerInstance.hasItems(icon.getItem()));
        }

        Builder whenItemCollected(ItemProviderEntry<?, ?> item) { // grant advancement when the specified ItemProviderEntry is collected
            return whenItemCollected(item.asStack()
                    .getItem());
        }

        Builder whenItemCollected(ItemLike itemProvider) { // grant advancement when the specified ItemLike is collected
            return trigger(InventoryChangeTrigger.TriggerInstance.hasItems(itemProvider));
        }

        Builder awardedForFree() { // grant automatically (used for root advancement)
            return trigger(InventoryChangeTrigger.TriggerInstance.hasItems(new ItemLike[]{}));
        }

        Builder trigger(Criterion<?> trigger) { // set a Criterion for the advancement
            mcBuilder.addCriterion(String.valueOf(keyIndex), trigger);
            keyIndex++;
            return this;
        }
    }
}
